### ISSUE TITLE
compile fails on CentOS7 with recent change to src/atmosphere/Atmosphere2D.cpp

### ISSUE THREAD

**Issue by hschwaiger-usgs** [chetzer-ncpa/ncpaprop-release#9]
Compilation fails on CentOS7 with the recent change to src/atmosphere/Atmosphere2D.cpp with the following error:
Atmosphere2D.cpp: In member function ‘void NCPA::Atmosphere2D::setup_ground_elevation_spline_from_file_()’:
Atmosphere2D.cpp:504:35: error: ‘gsl_interp_steffen’ was not declared in this scope
  topo_spline_ = gsl_spline_alloc( gsl_interp_steffen, np + 2 );
                                   ^
Atmosphere2D.cpp: In member function ‘void NCPA::Atmosphere2D::setup_ground_elevation_spline_from_profiles_()’:
Atmosphere2D.cpp:529:35: error: ‘gsl_interp_steffen’ was not declared in this scope
  topo_spline_ = gsl_spline_alloc( gsl_interp_steffen, np + 2 );

Reverting back to gsl_interp_cspline in these two line appears to fix the problem.

Code was configures with:
./configure --with-localpetsc --enable-autodependencies

**Comment by chetzer-ncpa** [comment]
Thanks for finding this.  It appears that CentOS still uses version 1.15 of the GSL, while my development Ubuntu machine has version 2.4.  gsl_interp_steffen was introduced in version 2.  I have added preprocessor directives to check the version number of GSL and use gsl_interp_cspline if it's not version 2 or higher.

Please pull and try again.
